.PHONY: clean All

All:
	@echo "----------Building project:[ ok-projekt - Debug ]----------"
	@"$(MAKE)" -f  "ok-projekt.mk"
clean:
	@echo "----------Cleaning project:[ ok-projekt - Debug ]----------"
	@"$(MAKE)" -f  "ok-projekt.mk" clean
